name: 20H2-VS2015


on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yatima1460
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: yatima1460
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build . --file WindowsServerCore20H2/VS2015.Dockerfile --tag yatima1460/windowsservercoreltsc20h2:vs2015 --tag ghcr.io/yatima1460/windowsservercoreltsc20h2:vs2015
      - run: docker push yatima1460/windowsservercoreltsc20h2:vs2015
      - run: docker push ghcr.io/yatima1460/windowsservercoreltsc20h2:vs2015