name: Publish Docker image


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  windowsservercoreltsc2019-vs2015-win81sdk:
    name: WindowsServerCoreLTSC-VS2015-Win8.1SDK
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file WindowsServerCoreLTSC-VS2015-Win8.1SDK.Dockerfile --tag yatima1460/windowsservercoreltsc2019:vs2015-win8.1sdk
      - name: Push to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/windowsservercoreltsc2019:vs2015-win8.1sdk
