name: Publish Docker image


on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  windowsservercoreltsc2019-vs2015-win81sdk:
    name: WindowsServerCoreLTSC-VS2015-Win8.1SDK
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the base 2015 Docker image
        run: docker build . --file WindowsServerCoreLTSC2019/VS2015.Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/windowsservercoreltsc2019:vs2015
      - name: Build the Win8.1SDK 2015 Docker image
        run: docker build . --file WindowsServerCoreLTSC2019/VS2015-Win8.1SDK.Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/windowsservercoreltsc2019:vs2015-win8.1sdk
      - name: Push 2015 to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/windowsservercoreltsc2019:vs2015
      - name: Push 2015 Win8.1SDK to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/windowsservercoreltsc2019:vs2015-win8.1sdk
