name: Docker Build


on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  windowsservercoreltsc2019-vs2015-win81sdk:
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yatima1460
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: yatima1460
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build . --file WindowsServerCoreLTSC2019/VS2015.Dockerfile --tag yatima1460/windowsservercoreltsc2019:vs2015 --tag ghcr.io/yatima1460/windowsservercoreltsc2019:vs2015
      - run: docker push yatima1460/windowsservercoreltsc2019:vs2015
      - run: docker push ghcr.io/yatima1460/windowsservercoreltsc2019:vs2015
      - run: docker build . --file WindowsServerCoreLTSC2019/VS2015-Win8.1SDK.Dockerfile --tag yatima1460/windowsservercoreltsc2019:vs2015-win8.1sdk --tag ghcr.io/yatima1460/windowsservercoreltsc2019:vs2015-win8.1sdk
      - run: docker push yatima1460/windowsservercoreltsc2019:vs2015-win8.1sdk
      - run: docker push ghcr.io/yatima1460/windowsservercoreltsc2019:vs2015-win8.1sdk
