name: windows_20h2_net35

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  build:
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: yatima1460
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: yatima1460
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir dummy-docker-context-dir
      - run: docker build --file windows_20h2_net35.Dockerfile --tag yatima1460/windows_20h2_net35 --tag ghcr.io/yatima1460/windows_20h2_net35 dummy-docker-context-dir
      - run: docker push yatima1460/windowsservercore20h2:vs2015-win8.1sdk
      - run: docker push ghcr.io/yatima1460/windowsservercore20h2:vs2015-win8.1sdk


